# Needs to match with config file names and the respective machine hostname.
HOSTNAMES=(vega licher) # Example: "vega.conf", vega is the hostname

BACKUP_DIR=/storage/Backups
BACKUP_DIR_HOST=licher

PROPAGATION_1=/home/nixy/mnt/Backups
PROPAGATION_1_HOST=vega

RSYNC_OPTS="--quiet --archive --recursive --acls --xattrs --hard-links -P --human-readable --verbose --itemize-changes --compress --delete"
