# Needs to match with config file names.
HOSTNAMES=(vega licher) # Example: "vega.conf", vega is the hostname

# Directories must be absolute and in local format,
# it doesn't matter if they are on different machines
BACKUP_DIR_1="/storage/Backups"
BACKUP_DIR_2="/home/nixy/mnt"

RSYNC_OPTS="--archive --recursive --acls --xattrs --hard-links -P --human-readable --verbose --itemize-changes --compress --delete"
