#!/usr/bin/env bash
git_conventional_commits_version=v2.7.2
ggshield_version=v1.45.0

git-conventional-commits init

echo "
# #
# Autogenerated file, manual changes will be overwritten
# #
repos:
  - repo: https://github.com/qoomon/git-conventional-commits
    rev: ${git_conventional_commits_version}
    hooks:
      - id: conventional-commits
  - repo: https://github.com/gitguardian/ggshield
    rev: ${ggshield_version}
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
" > .pre-commit-config.yaml

pre-commit install -t commit-msg
